// Code generated by fastssz. DO NOT EDIT.
package eth

import (
	github_com_OffchainLabs_prysm_v7_consensus_types_primitives "github.com/OffchainLabs/prysm/v7/consensus-types/primitives"
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the RequestAuth object
func (r *RequestAuth) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(r)
}

// MarshalSSZTo ssz marshals the RequestAuth object to a target array
func (r *RequestAuth) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Offset (0) 'Data'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(r.Data)

	// Field (1) 'Slot'
	dst = ssz.MarshalUint(dst, r.Slot)

	// Field (0) 'Data'
	if size := len(r.Data); size > 4096 {
		err = ssz.ErrBytesLengthFn("--.Data", size, 4096)
		return
	}
	dst = append(dst, r.Data...)

	return
}

// UnmarshalSSZ ssz unmarshals the RequestAuth object
func (r *RequestAuth) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Data'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Slot'
	r.Slot = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Slot](buf[4:12])

	// Field (0) 'Data'
	{
		buf = tail[o0:]
		if len(buf) > 4096 {
			return ssz.ErrBytesLength
		}
		if cap(r.Data) == 0 {
			r.Data = make([]byte, 0, len(buf))
		}
		r.Data = append(r.Data, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the RequestAuth object
func (r *RequestAuth) SizeSSZ() (size int) {
	size = 12

	// Field (0) 'Data'
	size += len(r.Data)

	return
}

// HashTreeRoot ssz hashes the RequestAuth object
func (r *RequestAuth) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(r)
}

// HashTreeRootWith ssz hashes the RequestAuth object with a hasher
func (r *RequestAuth) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(r.Data))
		if byteLen > 4096 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.AppendBytes32(r.Data)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (4096+31)/32)
	}

	// Field (1) 'Slot'
	ssz.PutUint(hh, r.Slot)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the SignedRequestAuth object
func (s *SignedRequestAuth) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedRequestAuth object to a target array
func (s *SignedRequestAuth) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)
	if s.Message == nil {
		s.Message = new(RequestAuth)
	}
	offset += s.Message.SizeSSZ()

	// Field (1) 'Signature'
	if size := len(s.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	dst = append(dst, s.Signature...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedRequestAuth object
func (s *SignedRequestAuth) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	if cap(s.Signature) == 0 {
		s.Signature = make([]byte, 0, len(buf[4:100]))
	}
	s.Signature = append(s.Signature, buf[4:100]...)

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if s.Message == nil {
			s.Message = new(RequestAuth)
		}
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedRequestAuth object
func (s *SignedRequestAuth) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(RequestAuth)
	}
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedRequestAuth object
func (s *SignedRequestAuth) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedRequestAuth object with a hasher
func (s *SignedRequestAuth) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	if size := len(s.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	hh.PutBytes(s.Signature)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BuilderPreferences object
func (b *BuilderPreferences) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPreferences object to a target array
func (b *BuilderPreferences) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'MaxExecutionPayment'
	dst = ssz.MarshalUint(dst, b.MaxExecutionPayment)

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPreferences object
func (b *BuilderPreferences) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 8 {
		return ssz.ErrSize
	}

	// Field (0) 'MaxExecutionPayment'
	b.MaxExecutionPayment = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Gwei](buf[0:8])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPreferences object
func (b *BuilderPreferences) SizeSSZ() (size int) {
	size = 8
	return
}

// HashTreeRoot ssz hashes the BuilderPreferences object
func (b *BuilderPreferences) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPreferences object with a hasher
func (b *BuilderPreferences) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'MaxExecutionPayment'
	ssz.PutUint(hh, b.MaxExecutionPayment)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BuilderPreferencesRequest object
func (b *BuilderPreferencesRequest) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPreferencesRequest object to a target array
func (b *BuilderPreferencesRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Field (0) 'Preferences'
	if b.Preferences == nil {
		b.Preferences = new(BuilderPreferences)
	}
	if dst, err = b.Preferences.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'Auth'
	dst = ssz.WriteOffset(dst, offset)
	if b.Auth == nil {
		b.Auth = new(SignedRequestAuth)
	}
	offset += b.Auth.SizeSSZ()

	// Field (1) 'Auth'
	if dst, err = b.Auth.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPreferencesRequest object
func (b *BuilderPreferencesRequest) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Preferences'
	if b.Preferences == nil {
		b.Preferences = new(BuilderPreferences)
	}
	if err = b.Preferences.UnmarshalSSZ(buf[0:8]); err != nil {
		return err
	}

	// Offset (1) 'Auth'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Auth'
	{
		buf = tail[o1:]
		if b.Auth == nil {
			b.Auth = new(SignedRequestAuth)
		}
		if err = b.Auth.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPreferencesRequest object
func (b *BuilderPreferencesRequest) SizeSSZ() (size int) {
	size = 12

	// Field (1) 'Auth'
	if b.Auth == nil {
		b.Auth = new(SignedRequestAuth)
	}
	size += b.Auth.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BuilderPreferencesRequest object
func (b *BuilderPreferencesRequest) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPreferencesRequest object with a hasher
func (b *BuilderPreferencesRequest) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Preferences'
	if err = b.Preferences.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Auth'
	if err = b.Auth.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}
